---

# handlers file for nfs_server
- name: start nfs server
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: started

- name: restart nfs server
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: restarted

- name: reload nfs server
  ansible.builtin.service:
    name: "{{ nfs_server_service }}"
    state: reloaded

- name: reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enable nfs-client
  ansible.builtin.systemd_service:
    name: nfs-client.target
    enabled: true

- name: start nfs-client
  ansible.builtin.systemd_service:
    name: nfs-client.target
    state: started
